;this file for FamiStudio Sound Engine generated by FamiStudio

parsec_music_data:
	db 8
	dw @instruments
	dw @samples-4
	dw @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4
	db <(@tempo_env_10_mid), >(@tempo_env_10_mid), 0, 0
	dw @song1ch0,@song1ch1,@song1ch2,@song1ch3,@song1ch4
	db <(@tempo_env_10_mid), >(@tempo_env_10_mid), 0, 0
	dw @song2ch0,@song2ch1,@song2ch2,@song2ch3,@song2ch4
	db <(@tempo_env_10_mid), >(@tempo_env_10_mid), 0, 0
	dw @song3ch0,@song3ch1,@song3ch2,@song3ch3,@song3ch4
	db <(@tempo_env_12_mid), >(@tempo_env_12_mid), 0, 0
	dw @song4ch0,@song4ch1,@song4ch2,@song4ch3,@song4ch4
	db <(@tempo_env_5_mid), >(@tempo_env_5_mid), 0, 0
	dw @song5ch0,@song5ch1,@song5ch2,@song5ch3,@song5ch4
	db <(@tempo_env_9_mid), >(@tempo_env_9_mid), 0, 0
	dw @song6ch0,@song6ch1,@song6ch2,@song6ch3,@song6ch4
	db <(@tempo_env_11_mid), >(@tempo_env_11_mid), 0, 0
	dw @song7ch0,@song7ch1,@song7ch2,@song7ch3,@song7ch4
	db <(@tempo_env_8_mid), >(@tempo_env_8_mid), 0, 0

@instruments:
	dw @env5,@env3,@env22,@env14
	dw @env21,@env3,@env25,@env20
	dw @env19,@env3,@env22,@env20
	dw @env12,@env3,@env22,@env20
	dw @env15,@env3,@env22,@env14
	dw @env0,@env3,@env22,@env14
	dw @env18,@env3,@env25,@env20
	dw @env29,@env3,@env23,@env20
	dw @env1,@env3,@env25,@env20
	dw @env11,@env3,@env22,@env20
	dw @env6,@env3,@env22,@env20
	dw @env17,@env3,@env22,@env20
	dw @env10,@env3,@env22,@env20
	dw @env13,@env3,@env25,@env24
	dw @env28,@env3,@env22,@env20
	dw @env28,@env3,@env22,@env24
	dw @env13,@env3,@env25,@env20
	dw @env27,@env3,@env25,@env20
	dw @env2,@env3,@env23,@env4
	dw @env11,@env3,@env22,@env20
	dw @env16,@env3,@env22,@env20
	dw @env7,@env3,@env25,@env20
	dw @env9,@env3,@env25,@env20
	dw @env7,@env3,@env25,@env4
	dw @env8,@env3,@env25,@env26
	dw @env10,@env3,@env22,@env20

@samples:
	db $00+<(FAMISTUDIO_DPCM_PTR),$0d,$0f,$40	;1 (BM Bass Drum)
	db $04+<(FAMISTUDIO_DPCM_PTR),$1f,$0f,$40	;2 (BM Tom 1)
	db $0c+<(FAMISTUDIO_DPCM_PTR),$1f,$0f,$40	;3 (BM Tom 2)
	db $0c+<(FAMISTUDIO_DPCM_PTR),$1f,$0e,$40	;4 (BM Tom 2)
	db $0c+<(FAMISTUDIO_DPCM_PTR),$1f,$0c,$40	;5 (BM Tom 2)
	db $14+<(FAMISTUDIO_DPCM_PTR),$10,$0f,$40	;6 (NG Bass Drum)
	db $18+<(FAMISTUDIO_DPCM_PTR),$20,$0f,$40	;7 (NG Snare)

@env0:
	db $07,$c4,$c6,$c8,$ca,$00,$04,$c6,$c3,$00,$08
@env1:
	db $00,$cf,$cc,$c9,$c6,$c3,$c0,$00,$06
@env2:
	db $04,$ca,$7f,$00,$01
@env3:
	db $c0,$7f,$00,$00
@env4:
	db $00,$be,$7f,$00,$01
@env5:
	db $00,$cf,$08,$c0,$00,$03
@env6:
	db $00,$c8,$c6,$c5,$c4,$c2,$c0,$00,$06
@env7:
	db $00,$c9,$c7,$c5,$c4,$00,$04
@env8:
	db $0a,$ca,$c9,$c8,$c7,$c6,$c5,$c4,$00,$07,$c3,$c2,$c1,$c0,$00,$0d
@env9:
	db $00,$ce,$cd,$cb,$c9,$c7,$c3,$c3,$c2,$c2,$c1,$c0,$00,$0b
@env10:
	db $04,$cf,$7f,$00,$01
@env11:
	db $00,$c8,$c9,$ca,$02,$c9,$c9,$c8,$c8,$c7,$c7,$c6,$c6,$c5,$02,$c4,$02,$c3,$02,$c2,$03,$c1,$02,$c0,$00,$17
@env12:
	db $04,$c6,$7f,$00,$01
@env13:
	db $0a,$ce,$cd,$cc,$cb,$ca,$c9,$c8,$00,$07,$c7,$c6,$c5,$c4,$c2,$c1,$c0,$00,$10
@env14:
	db $00,$c0,$c0,$c1,$c1,$c2,$c2,$c1,$c1,$c0,$c0,$bf,$bf,$be,$be,$bf,$bf,$00,$01
@env15:
	db $07,$c6,$c9,$cc,$cf,$00,$04,$c9,$c3,$00,$08
@env16:
	db $00,$c5,$c4,$c3,$c2,$c1,$c0,$00,$06
@env17:
	db $00,$c7,$04,$c0,$00,$03
@env18:
	db $00,$cc,$ca,$c8,$c6,$00,$04
@env19:
	db $00,$c7,$c7,$c6,$c5,$c2,$c0,$02,$c3,$c3,$c2,$c1,$c0,$03,$c3,$c3,$c2,$c1,$c0,$03,$c3,$c3,$c2,$c1,$c0,$00,$18
@env20:
	db $00,$c0,$7f,$00,$01
@env21:
	db $00,$c6,$c8,$ca,$cc,$c0,$0b,$c4,$c6,$c8,$ca,$c0,$0b,$c2,$c4,$c6,$c8,$00,$0b
@env22:
	db $7f,$00,$00
@env23:
	db $c2,$7f,$00,$00
@env24:
	db $00,$c0,$c0,$c1,$c1,$c2,$c2,$c3,$c3,$c2,$c2,$c1,$c1,$00,$01
@env25:
	db $c1,$7f,$00,$00
@env26:
	db $00,$be,$be,$bf,$bf,$c0,$c0,$c1,$c1,$c0,$c0,$bf,$bf,$00,$01
@env27:
	db $0c,$cf,$cd,$cb,$ca,$c9,$c8,$c7,$c6,$c6,$00,$09,$c4,$c3,$c2,$c1,$c0,$04,$c2,$c4,$c6,$c5,$c4,$c3,$c2,$c1,$c0,$c0,$c1,$c3,$c5,$c4,$c3,$c2,$c1,$c0,$03,$c2,$c4,$c3,$c2,$c1,$c0,$00,$2a
@env28:
	db $07,$cc,$ca,$c8,$c6,$00,$04,$c5,$c5,$c4,$c4,$c3,$c3,$c2,$c2,$c1,$c1,$c0,$00,$11
@env29:
	db $00,$c8,$cc,$cc,$c8,$00,$04
@tempo_env_10_mid:
	db $03,$04,$06,$05,$05,$05,$80
@tempo_env_12_mid:
	db $03,$05,$05,$80
@tempo_env_5_mid:
	db $03,$04,$07,$04,$05,$05,$80
@tempo_env_9_mid:
	db $03,$06,$04,$05,$80
@tempo_env_11_mid:
	db $03,$05,$05,$04,$06,$06,$04,$05,$05,$05,$05,$05,$80
@tempo_env_8_mid:
	db $03,$05,$04,$06,$05,$80
@song0ch0:
@song0ref1:
	db $ae, $24, $a7, $24, $91, $24, $91, $24, $91, $24, $91, $24, $91, $24, $8f, $24, $93, $24, $91, $24, $8f, $27, $91, $29
	db $a7, $29, $91, $29, $8f, $6b, $24, $a7, $24, $91, $24, $91, $24, $91, $24, $91, $24, $91, $24, $91, $24, $91, $24, $91
	db $24, $8f, $29, $91, $27, $a7, $27, $91, $27, $8f
@song0ch0loop:
	db $6a, <(@tempo_env_10_mid), >(@tempo_env_10_mid)
	db $ff, $38
	dw @song0ref1
	db $6b, $9a, $29, $a5, $2c, $91, $2e, $a5, $30, $91, $2e, $91, $2c, $a5, $2e, $91, $27, $91, $f9, $91, $29, $b9, $00, $91
	db $6b, $29, $a5, $29, $91, $2c, $91, $f9, $91, $2c, $f7, $a5, $f9, $b9, $6b, $29, $a5, $2c, $91, $2e, $a5, $30, $91, $2e
	db $91, $2c, $a5, $33, $91, $27, $91, $f9, $91, $29, $b9, $00, $91, $6b, $2c, $a5, $2c, $91, $2e, $a5, $29, $f7, $a5, $f9
	db $b9, $6b, $35, $a5, $3c, $91, $3a, $a5, $38, $a5, $38, $91, $37, $a5, $33, $a5, $35, $cd, $6b, $61, $f8, $2e, $31, $91
	db $62, $31, $e1, $33, $a5, $30, $f5, $f9, $a5, $6b, $2c, $91, $2e, $a5, $2e, $a5, $2e, $a5, $30, $91, $2c, $f5, $f9, $a5
	db $6b, $2c, $a5, $2c, $a5, $2c, $a5, $2e, $a5, $29, $f7, $a3, $f9, $6b, $93, $35, $91, $30, $91, $29, $91, $35, $91, $30
	db $91
@song0ref211:
	db $29, $91, $35, $91, $30, $91, $29, $91, $00, $2e, $a3, $2e, $a5, $2e, $91, $f9, $91, $6b, $00, $91, $33, $91, $2e, $91
	db $27, $91, $33, $91, $2e, $91
@song0ref241:
	db $27, $91, $33, $91, $2e, $91, $27, $91, $00, $2c, $a3, $2c, $a5, $2c, $91, $f9, $91, $6b, $00, $91, $31, $91, $2c, $91
	db $25, $91, $31, $91, $2c, $91, $25, $91, $31, $91, $2c, $91, $25, $91, $00, $2a, $a3, $2a, $a5, $2a, $a5, $6b, $2e, $a5
	db $2e, $a5, $2e, $a5, $2e, $a5, $29, $f7, $a5, $6b, $f7, $a7, $f9, $f7, $a5, $fd
	dw @song0ch0loop
@song0ch1:
@song0ref307:
	db $a0
@song0ref308:
	db $1d, $a5, $1d, $91, $20, $91, $1d, $91, $1d, $91, $1d, $91, $20, $8f, $1d, $93, $1d, $91, $1d, $91, $20, $91, $22, $a5
	db $22, $91, $22, $91, $1d, $a5, $1d, $91, $20, $91, $1d, $91, $1d, $91, $1d, $91, $20, $91, $1d, $91, $1d, $91, $1d, $91
	db $22, $91, $20, $a5, $20, $91, $20, $91
@song0ch1loop:
	db $ff, $38
	dw @song0ref307
	db $ff, $38
	dw @song0ref308
	db $ff, $38
	dw @song0ref308
	db $ff, $38
	dw @song0ref308
	db $ff, $38
	dw @song0ref308
	db $00, $b9, $b0, $35, $91, $30, $91, $29, $91, $35, $93, $30, $8f
	db $ff, $11
	dw @song0ref211
	db $00, $91, $33, $91, $2e, $91, $27, $91, $33, $93, $2e, $8f
	db $ff, $11
	dw @song0ref241
	db $00, $91, $31, $91, $2c, $91, $25, $91, $31, $93, $2c, $8f, $25, $91, $31, $91, $2c, $91, $25, $91, $2a, $a5, $2a, $a5
	db $2a, $a5, $00, $2e, $a5, $2e, $a5, $2e, $a5, $2e, $91, $29, $f7, $8f, $f7, $bb, $f9, $f7, $91, $fd
	dw @song0ch1loop
@song0ch2:
@song0ref457:
	db $b2
@song0ref458:
	db $1d, $a3, $00, $1d, $8f, $00, $20, $8f, $00, $1d, $8f, $00, $1d, $8f, $00, $1d, $8f, $00, $20, $8f, $00, $1d, $8f, $00
	db $1d, $8f, $00, $1d, $8f, $00, $20, $8f, $00, $22, $a3, $00, $22, $8f, $00, $22, $8f, $00, $1d, $a3, $00
@song0ref503:
	db $1d, $8d, $00, $81, $20, $8d, $00, $81, $1d, $8d, $00, $81, $1d, $8d, $00, $81
	db $ff, $10
	dw @song0ref503
@song0ref522:
	db $1d, $8d, $00, $81, $22, $8d
@song0ref528:
	db $00, $81, $20, $a1, $00, $81, $20, $8d, $00, $81, $20, $8d, $00, $81
@song0ch2loop:
	db $ff, $3d
	dw @song0ref457
	db $ff, $10
	dw @song0ref503
	db $ff, $14
	dw @song0ref522
@song0ref552:
	db $1d, $a1
@song0ref554:
	db $00, $81, $1d, $8d, $00, $81, $1d, $8d, $00, $81, $1d, $8d, $00, $81, $1d, $8d
	db $ff, $10
	dw @song0ref554
@song0ref573:
	db $00, $81, $1d, $8d, $00, $81, $20, $8d
@song0ref581:
	db $00, $81, $22, $a1, $00, $81, $22, $8d, $00, $81, $22, $8d, $00, $81
	db $ff, $12
	dw @song0ref552
	db $ff, $10
	dw @song0ref554
	db $00, $81
	db $ff, $11
	dw @song0ref522
	db $91
	db $ff, $12
	dw @song0ref552
	db $ff, $10
	dw @song0ref554
	db $ff, $16
	dw @song0ref573
	db $ff, $12
	dw @song0ref552
	db $ff, $10
	dw @song0ref554
	db $00, $81
	db $ff, $11
	dw @song0ref522
	db $91
	db $ff, $12
	dw @song0ref552
	db $ff, $10
	dw @song0ref554
	db $ff, $16
	dw @song0ref573
	db $ff, $12
	dw @song0ref552
	db $ff, $10
	dw @song0ref554
	db $00, $81
	db $ff, $11
	dw @song0ref522
	db $91
	db $ff, $12
	dw @song0ref552
	db $ff, $10
	dw @song0ref554
	db $ff, $16
	dw @song0ref573
	db $ff, $12
	dw @song0ref552
	db $ff, $10
	dw @song0ref554
	db $00, $81
	db $ff, $11
	dw @song0ref522
	db $91, $1d, $a1, $00, $81, $1d, $a1, $00, $81, $1d, $a1, $00, $81, $1d, $a1, $00, $81, $1d, $a1, $00, $81, $1d, $a1
	db $ff, $0e
	dw @song0ref581
	db $1b, $a1, $00, $81, $1b, $a1, $00, $81, $1b, $a1, $00, $81, $1b, $a1, $00, $81, $1b, $a1, $00, $81, $1b, $a1
	db $ff, $0e
	dw @song0ref528
	db $19, $a1, $00, $81, $19, $a1, $00, $81, $19, $a1, $00, $81, $19, $a1, $00, $81, $19, $a1, $00, $81, $19, $a1, $00, $81
	db $1e, $a1, $00, $81, $1e, $8d, $00, $81, $1e, $8d, $00, $81
	db $ff, $3d
	dw @song0ref458
	db $ff, $10
	dw @song0ref503
	db $ff, $14
	dw @song0ref522
	db $fd
	dw @song0ch2loop
@song0ch3:
	db $f7, $f7, $cf, $f7, $f7, $cf
@song0ch3loop:
@song0ref775:
	db $f7, $f7, $cf, $f7, $f7, $cf, $f7, $f7, $cf, $f7, $f7, $cf, $f7, $f7, $cf
	db $ff, $0f
	dw @song0ref775
	db $f7, $f7, $cf, $f7, $f7, $cf, $f7, $f7, $cf, $f7, $a7, $a6, $1a, $a5, $00, $f5, $f7, $f7, $cf, $fd
	dw @song0ch3loop
@song0ch4:
@song0ref815:
	db $93, $06, $a5, $07, $a5, $06, $91, $06, $91, $07, $a5, $06, $a5, $07, $a5, $06, $91, $06, $91, $07, $91
	db $ff, $15
	dw @song0ref815
@song0ch4loop:
	db $ff, $15
	dw @song0ref815
	db $ff, $15
	dw @song0ref815
	db $ff, $15
	dw @song0ref815
	db $ff, $15
	dw @song0ref815
	db $ff, $15
	dw @song0ref815
	db $ff, $15
	dw @song0ref815
	db $ff, $15
	dw @song0ref815
	db $ff, $15
	dw @song0ref815
	db $ff, $15
	dw @song0ref815
	db $ff, $15
	dw @song0ref815
	db $93
@song0ref871:
	db $07, $91, $07, $91, $06, $a5, $07, $91, $07, $91, $06, $a5, $07, $87, $07, $87, $07, $87, $07, $87, $06, $a5, $04, $91
	db $04, $91, $06, $91, $00, $91
	db $ff, $1e
	dw @song0ref871
	db $ff, $1c
	dw @song0ref871
	db $03, $87, $03, $87, $03, $87, $03, $87, $02, $87, $02, $87, $02, $87, $02, $87, $04, $87, $04, $87, $04, $87, $04, $87
	db $06, $91, $06, $91, $00, $91, $06, $a5, $07, $a5, $06, $91, $06, $91, $07, $91
	db $ff, $15
	dw @song0ref815
	db $fd
	dw @song0ch4loop
@song1ch0:
@song1ch0loop:
	db $6a, <(@tempo_env_10_mid), >(@tempo_env_10_mid), $aa
@song1ref6:
	db $18, $a5, $ac, $18, $91, $18, $91, $18, $91, $18, $91, $18, $91, $aa, $18, $b9, $ac, $18, $91, $18, $91, $18, $91, $18
	db $91, $18, $91, $aa, $18, $91, $6b, $a7, $ac, $18, $91, $18, $91, $18, $91, $18, $91, $18, $91, $aa, $22, $a5, $20, $a5
	db $1f, $a5, $1b, $b9, $6b
	db $ff, $2d
	dw @song1ref6
	db $6b
	db $ff, $2d
	dw @song1ref6
	db $6b
	db $ff, $2d
	dw @song1ref6
	db $6b
	db $ff, $2d
	dw @song1ref6
	db $6b
	db $ff, $2d
	dw @song1ref6
	db $6b
	db $ff, $2d
	dw @song1ref6
	db $6b
	db $ff, $2d
	dw @song1ref6
	db $6b
	db $ff, $2d
	dw @song1ref6
	db $6b
	db $ff, $2d
	dw @song1ref6
	db $6b
	db $ff, $2d
	dw @song1ref6
	db $6b
	db $ff, $2d
	dw @song1ref6
	db $fd
	dw @song1ch0loop
@song1ch1:
@song1ch1loop:
@song1ref106:
	db $aa
@song1ref107:
	db $11, $a5, $ac, $11, $91, $11, $91, $11, $91, $11, $91, $11, $91, $aa, $11, $b9, $ac, $11, $91, $11, $91, $11, $91, $11
	db $91, $11, $91, $aa, $11, $91, $a7, $ac, $11, $91, $11, $91, $11, $91, $11, $91, $11, $91, $aa, $1b, $a5, $19, $a5, $18
	db $a5, $14, $b9
	db $ff, $2d
	dw @song1ref107
	db $a2
@song1ref162:
	db $29, $cd, $2c, $91, $2e, $91, $30, $91, $2e, $a5, $2c, $a5, $2b, $a5, $29, $a5, $27, $91, $93, $27, $b9, $25, $a5, $25
	db $91, $29, $a5, $f9, $f7, $91, $29, $cd, $30, $a5, $2e, $91, $2c, $a5, $2b, $a5, $2c, $a5, $2e, $b9, $2b, $a5, $2b, $91
	db $2b, $91, $27, $a5, $27, $91, $29, $a5, $f9, $f7, $91
	db $ff, $3b
	dw @song1ref162
	db $ff, $2d
	dw @song1ref106
	db $ff, $2d
	dw @song1ref107
	db $a2
@song1ref231:
	db $30, $91, $f9, $b9, $2e, $91, $f9, $b9, $2c, $91, $f9, $b9, $27, $a5, $29, $a5, $2c, $a5, $2e, $91, $f9, $a5, $27, $91
	db $f9, $91, $27, $a5, $f9, $f7, $91, $2c, $91, $f9, $b9, $25, $91, $f9, $91, $25, $a5, $f9, $f5, $20, $91, $22, $91, $93
	db $25, $a5, $27, $a5, $29, $a5, $27, $a5, $f9, $f7, $91
	db $ff, $32
	dw @song1ref231
	db $2c, $a5, $29, $a5, $27, $a5, $f9, $f7, $91, $fd
	dw @song1ch1loop
@song1ch2:
@song1ch2loop:
	db $b2
@song1ref307:
	db $1d, $a3, $00, $1d, $85, $00, $89, $1d, $85, $00, $89, $1d, $85, $00, $89, $1d, $85, $00, $89, $1d, $85, $00, $89, $1d
	db $b7, $00, $1d, $85, $00, $89, $1d, $85, $00, $89, $1d, $85, $00, $89, $1d, $85, $00, $89, $1d, $87, $00, $87, $1d, $91
	db $a5, $00, $1d, $85, $00, $89, $1d, $85, $00, $89, $1d, $85, $00, $89, $1d, $85, $00, $89, $1d, $85, $00, $89, $27, $a5
	db $25, $a5, $24, $a5, $20, $b7, $00
	db $ff, $4f
	dw @song1ref307
	db $ff, $4f
	dw @song1ref307
	db $ff, $4f
	dw @song1ref307
	db $ff, $4f
	dw @song1ref307
	db $ff, $4f
	dw @song1ref307
	db $ff, $4f
	dw @song1ref307
	db $ff, $4f
	dw @song1ref307
	db $ff, $4f
	dw @song1ref307
	db $ff, $4f
	dw @song1ref307
	db $ff, $4f
	dw @song1ref307
	db $ff, $4f
	dw @song1ref307
	db $fd
	dw @song1ch2loop
@song1ch3:
@song1ch3loop:
@song1ref423:
	db $a8
@song1ref424:
	db $19, $91, $19, $91, $19, $91, $19, $91, $19, $91, $19, $91, $19, $91, $19, $91, $19, $91, $19, $91, $19, $91, $19, $91
	db $19, $91, $19, $91, $19, $91
	db $ff, $1e
	dw @song1ref424
	db $ff, $1e
	dw @song1ref424
	db $ff, $1e
	dw @song1ref424
	db $ff, $1e
	dw @song1ref424
	db $ff, $1e
	dw @song1ref424
	db $ff, $1e
	dw @song1ref424
	db $ff, $1e
	dw @song1ref424
	db $19, $91, $19, $91, $19, $91, $19, $87, $19, $87, $19, $91, $a6, $1a, $a5
	db $ff, $1e
	dw @song1ref423
	db $ff, $1e
	dw @song1ref424
	db $ff, $1e
	dw @song1ref424
	db $ff, $1e
	dw @song1ref424
	db $19, $87, $19, $87, $19, $91, $a6, $1a, $a5
	db $ff, $1e
	dw @song1ref423
	db $ff, $1e
	dw @song1ref424
	db $ff, $1e
	dw @song1ref424
	db $ff, $1e
	dw @song1ref424
	db $ff, $1e
	dw @song1ref424
	db $ff, $1e
	dw @song1ref424
	db $ff, $1e
	dw @song1ref424
	db $ff, $1e
	dw @song1ref424
	db $19, $91, $19, $91, $19, $91, $19, $91, $19, $87, $19, $87, $19, $91, $a6, $1a, $a5
	db $ff, $1e
	dw @song1ref423
	db $ff, $1e
	dw @song1ref424
	db $ff, $1e
	dw @song1ref424
	db $ff, $1e
	dw @song1ref424
	db $19, $87, $19, $87, $19, $91, $a6, $1a, $a5, $a8, $19, $91, $fd
	dw @song1ch3loop
@song1ch4:
@song1ch4loop:
@song1ref580:
	db $06
@song1ref581:
	db $cd, $06, $cd, $06, $cd, $06, $cd, $06, $cd, $06, $cd, $06, $cd, $06, $cd, $06, $cd, $06, $cd, $06, $cd, $06, $cd, $06
	db $cd, $06, $cd, $06, $cd
	db $ff, $1e
	dw @song1ref580
	db $06, $a5, $03, $91, $04, $87, $04, $87, $05
	db $ff, $1d
	dw @song1ref581
	db $06, $a5, $03, $91, $04, $87, $04, $87, $05
	db $ff, $1d
	dw @song1ref581
	db $ff, $1e
	dw @song1ref580
	db $06, $cd, $06, $a5, $03, $91, $04, $87, $04, $87, $05
	db $ff, $1d
	dw @song1ref581
	db $06, $a5, $03, $91, $04, $87, $04, $87, $05, $cd, $fd
	dw @song1ch4loop
@song2ch0:
	db $f7, $f7
@song2ch0loop:
	db $6a, <(@tempo_env_10_mid), >(@tempo_env_10_mid)
@song2ref7:
	db $9c
@song2ref8:
	db $1e, $b9
@song2ref10:
	db $25, $a5, $24, $91, $9e, $23, $cd, $00, $a5, $6b, $9c, $1e, $b9, $25, $a5, $24, $91, $23, $91, $24, $91, $23, $91, $21
	db $a7, $00, $8f, $6b, $9e, $1e, $b9, $9c
	db $ff, $18
	dw @song2ref10
@song2ref45:
	db $6b, $25, $a5, $25, $91, $24, $a5, $24, $91, $23, $a5, $23, $91, $21, $a5, $21, $91, $6b, $1e, $a5, $1e, $91, $21, $a5
	db $9e, $1e, $bb, $00, $cb, $6b
	db $ff, $1c
	dw @song2ref7
	db $9c
	db $ff, $18
	dw @song2ref10
	db $ff, $1a
	dw @song2ref45
	db $6b, $9c
@song2ref87:
	db $12, $b9, $19, $a5, $18, $91, $17, $cd, $00, $a5, $6b
@song2ref98:
	db $12, $b9, $19, $a5, $18, $91, $17, $91, $18, $91, $17, $91, $15, $a5, $00, $91, $6b
	db $ff, $1a
	dw @song2ref87
	db $6b
@song2ref119:
	db $19, $a3, $00, $19, $91, $18, $a3, $00, $18, $91, $17, $a3, $00, $17, $91, $15, $a3, $00, $15, $91, $6b, $12, $a3, $00
	db $12, $91, $15, $a5, $12, $b9, $00, $cd, $6b
	db $ff, $1c
	dw @song2ref8
	db $9c
	db $ff, $18
	dw @song2ref10
	db $ff, $1a
	dw @song2ref45
	db $6b
	db $ff, $1c
	dw @song2ref7
	db $9c
	db $ff, $18
	dw @song2ref10
	db $ff, $1a
	dw @song2ref45
	db $fd
	dw @song2ch0loop
@song2ch1:
	db $f7, $f7
@song2ch1loop:
	db $f7, $f7, $f7, $f7, $f7, $f7, $f7, $f7, $f7, $f7, $f7, $f7
@song2ref191:
	db $9c, $2a, $a5, $2a, $91, $31, $a5, $9e, $2f, $e1, $00, $a5, $9c, $2a, $b9, $31, $a5, $2f, $91, $2d, $91, $2c, $91, $2b
	db $91, $9e, $2a, $a5, $00, $91
	db $ff, $1a
	dw @song2ref191
	db $9c, $61, $f4, $2f, $34, $91, $9e, $34, $91, $9c, $32, $91, $31, $a5, $9e, $2f, $b9, $9c, $2d, $91, $2c, $a5, $9e, $2a
	db $91, $a7, $9c, $29, $91, $2c, $a5, $9e, $2a, $b9, $00, $cd, $a4, $12, $b9, $19, $a5, $18, $91, $17, $cd, $00, $a5
	db $ff, $10
	dw @song2ref98
	db $12, $b9, $19, $a5, $18, $91, $17, $cd, $00, $a5
	db $ff, $10
	dw @song2ref98
	db $ff, $14
	dw @song2ref119
	db $12, $a3, $00, $12, $91, $15, $a5, $12, $b9, $00, $cd, $9c, $61, $ed, $2e, $36, $91, $9e, $36, $f7, $e1, $9c, $3d, $bb
	db $3b, $a3, $3d, $cd, $39, $b9, $9e, $38, $f5, $36, $f5, $38, $f5, $39, $f5, $36, $f7, $f5, $9c, $3e, $91, $3d, $91, $3e
	db $91, $3d, $91, $3b, $91, $3d, $91, $39, $a5, $38, $a5, $39, $a5, $9e, $38, $f5, $36, $f5, $3b, $f5, $9c, $38, $b9, $39
	db $b9, $36, $a5, $36, $91, $3d, $a5, $9e, $3b, $e1, $00, $a5, $9c, $36, $b9, $3d, $a5, $3b, $91, $39, $91, $38, $91, $37
	db $91, $9e, $36, $a5, $00, $91, $9c, $61, $fa, $3b, $40, $91, $9e, $40, $91, $9c, $3e, $91, $3d, $a5, $9e, $3b, $b9, $9c
	db $39, $91, $38, $a5, $9e, $36, $91, $a7, $9c, $35, $91, $38, $a5, $9e, $36, $b9, $00, $cd, $fd
	dw @song2ch1loop
@song2ch2:
	db $f7, $f7
@song2ch2loop:
	db $b2
@song2ref435:
	db $1e, $b9, $25, $a5, $24, $91, $23, $cd, $00, $a5, $1e, $b9, $25, $a5, $24, $91, $23, $91, $24, $91, $23, $91, $21, $a5
	db $00, $91
	db $ff, $1a
	dw @song2ref435
@song2ref464:
	db $25, $a3, $00, $25, $91, $24, $a3, $00, $24, $91, $23, $a3, $00, $23, $91, $21, $a3, $00, $21, $91, $1e, $a3, $00, $1e
	db $91, $21, $a5, $1e, $b9, $00, $cd
	db $ff, $1a
	dw @song2ref435
	db $ff, $1a
	dw @song2ref435
	db $ff, $1f
	dw @song2ref464
	db $f7, $f7, $f7, $f7, $61, $fa, $3b, $40, $91, $62, $40, $91, $43, $91, $47, $a5, $45, $b9, $43, $91, $47, $a5, $45, $91
	db $a7, $43, $91, $47, $a5, $45, $b9, $43, $91, $42, $b9, $61, $fa, $3b, $40, $91, $62, $40, $91, $43, $91, $47, $a5, $45
	db $b9, $43, $91, $42, $a5, $40, $91, $a7, $3e, $91, $42, $a7, $40, $b7, $00, $cd
	db $ff, $1a
	dw @song2ref435
	db $ff, $1a
	dw @song2ref435
	db $ff, $1f
	dw @song2ref464
	db $ff, $1a
	dw @song2ref435
	db $ff, $1a
	dw @song2ref435
	db $ff, $1f
	dw @song2ref464
	db $fd
	dw @song2ch2loop
@song2ch3:
	db $bb, $a8, $19, $f5, $19, $b9
@song2ch3loop:
	db $bb, $a8
@song2ref598:
	db $19, $f5, $19, $b9, $bb, $19, $f5, $19, $b9, $bb, $19, $f5, $19, $b9, $bb
	db $ff, $0f
	dw @song2ref598
	db $ff, $0f
	dw @song2ref598
	db $ff, $0f
	dw @song2ref598
	db $ff, $0f
	dw @song2ref598
	db $ff, $0f
	dw @song2ref598
	db $ff, $0f
	dw @song2ref598
	db $ff, $0f
	dw @song2ref598
	db $ff, $0f
	dw @song2ref598
	db $ff, $0e
	dw @song2ref598
	db $fd
	dw @song2ch3loop
@song2ch4:
	db $01, $f5, $01, $a5, $01, $cd
@song2ch4loop:
@song2ref650:
	db $01, $f5, $01, $a5, $01, $cd, $01, $f5, $01, $a5, $01, $cd, $01, $f5, $01, $a5, $01, $cd
	db $ff, $12
	dw @song2ref650
	db $ff, $12
	dw @song2ref650
	db $ff, $12
	dw @song2ref650
	db $ff, $12
	dw @song2ref650
	db $ff, $12
	dw @song2ref650
	db $ff, $12
	dw @song2ref650
	db $ff, $12
	dw @song2ref650
	db $ff, $12
	dw @song2ref650
	db $ff, $12
	dw @song2ref650
	db $fd
	dw @song2ch4loop
@song3ch0:
@song3ch0loop:
	db $6a, <(@tempo_env_12_mid), >(@tempo_env_12_mid), $8e, $25, $95, $20, $f7, $95, $00, $95, $1c, $95, $19, $95, $19, $95
	db $19, $95, $00, $dd, $6b, $1c, $95, $1e, $95, $21, $ad, $25, $f7, $ad, $00, $ad, $28, $c5, $6b, $31, $c5, $32, $dd, $00
	db $ad, $36, $95, $00, $dd, $39, $ad, $6b, $36, $f7, $ad, $00, $ad, $2a, $dd, $26, $ad, $23, $95, $6b, $00, $f7, $95, $19
	db $95, $00, $ad, $19, $95, $00, $f7, $95, $6b, $1a, $ad, $00, $c5, $23, $95, $23, $95, $21, $f5, $26, $c5, $28, $95, $6b
	db $25, $ad, $21, $95, $1c, $c5, $1c, $95, $1e, $ad, $1e, $f5, $21, $95, $26, $95, $6b, $2a, $ad, $2c, $ad, $2f, $95, $34
	db $f7, $ad, $00, $dd, $6b, $2a, $95, $26, $95, $26, $95, $21, $f5, $21, $f7, $ad, $1e, $95, $6b, $1e, $c5, $21, $f7, $f7
	db $95, $25, $95, $2a, $95, $6b, $26, $ad, $28, $c5, $23, $dd, $21, $c5, $21, $ad, $00, $ad, $6b, $25, $f7, $95, $28, $ad
	db $00, $ad, $26, $c5, $21, $95, $23, $95, $21, $95, $6b, $21, $f5, $25, $95, $28, $f7, $f5, $6b, $2a, $ad, $2c, $95, $2f
	db $ad, $00, $95, $25, $f7, $f5, $6b, $1e, $dd, $19, $95, $1e, $ad, $23, $95, $20, $95, $00, $ad, $1a, $dd, $1c, $95, $6b
	db $21, $c5, $23, $dd, $28, $c5, $26, $dd, $00, $ad, $fd
	dw @song3ch0loop
@song3ch1:
@song3ch1loop:
	db $8e, $25, $c5, $21, $95, $25, $95, $00, $c5, $25, $95, $00, $ad, $1e, $95, $00, $95, $25, $95, $21, $ad, $1c, $95, $1a
	db $95, $19, $95, $15, $ad, $14, $dd, $12, $ad, $12, $ad, $00, $95, $15, $95, $14, $95, $17, $dd, $1c, $dd, $00, $ad, $1e
	db $95, $1a, $95, $20, $ad, $20, $ad, $25, $c5, $28, $f7, $95, $00, $f7, $ad, $1a, $f7, $f7, $95, $1c, $c5, $20, $ad, $00
	db $95, $20, $95, $21, $f5, $21, $ad, $1c, $f7, $ad, $17, $dd, $14, $95, $0e, $f7, $f5, $0d, $95, $0d, $ad, $12, $ad, $0d
	db $ad, $0d, $f7, $ad, $0d, $c5, $12, $c5, $0e, $f7, $95, $10, $c5, $12, $dd, $0e, $95, $0d, $f7, $95, $0e, $f5, $0e, $dd
	db $0e, $95, $14, $f7, $f7, $c5, $15, $95, $19, $95, $14, $95, $0e, $95, $10, $ad, $00, $ad, $0d, $95, $00, $f7, $c5, $0d
	db $95, $00, $dd, $0e, $ad, $0e, $ad, $12, $ad, $15, $95, $1a, $c5, $1c, $95, $1e, $95, $21, $c5, $1e, $ad, $23, $95, $25
	db $f7, $f5, $00, $95, $2a, $c5, $00, $ad, $2d, $c5, $2f, $c5, $2f, $95, $2f, $95, $2f, $95, $2c, $95, $00, $95, $23, $95
	db $20, $f7, $dd, $23, $ad, $00, $95, $21, $ad, $fd
	dw @song3ch1loop
@song3ch2:
@song3ch2loop:
	db $98, $28, $ad, $25, $ad, $21, $f5, $21, $f7, $95, $23, $95, $26, $ad, $28, $95, $28, $f7, $c5, $2c, $dd, $31, $95, $1c
	db $c5, $00, $f7, $f7, $c5, $19, $c5, $17, $f7, $dd, $15, $dd, $14, $f7, $f5, $12, $95, $15, $f5, $12, $ad, $00, $95, $14
	db $f7, $f7, $ad, $0e, $95, $12, $95, $0d, $ad, $0e, $95, $0d, $dd, $0d, $f7, $ad, $0d, $95, $0d, $dd, $0d, $dd, $0d, $dd
	db $12, $95, $10, $c5, $14, $ad, $10, $95, $00, $95, $12, $ad, $14, $f7, $f5, $00, $95, $17, $f7, $f7, $f5, $19, $ad, $1a
	db $dd, $00, $f7, $ad, $17, $ad, $17, $95, $14, $ad, $0e, $c5, $00, $95, $15, $f7, $f5, $19, $95, $17, $f5, $00, $f7, $95
	db $17, $95, $1a, $c5, $1a, $95, $00, $f7, $ad, $1e, $f7, $95, $00, $95, $23, $95, $23, $ad, $21, $f7, $95, $26, $ad, $28
	db $95, $28, $f5, $2d, $f7, $ad, $2d, $f7, $dd, $fd
	dw @song3ch2loop
@song3ch3:
@song3ch3loop:
	db $90
@song3ref588:
	db $20, $dd, $96, $36, $f7, $f7, $ad, $90, $20, $dd, $96, $36, $dd, $94, $29, $f7, $95, $90, $20, $ad
	db $ff, $0f
	dw @song3ref588
	db $ff, $0f
	dw @song3ref588
	db $ff, $0f
	dw @song3ref588
	db $ff, $0f
	dw @song3ref588
	db $ff, $0f
	dw @song3ref588
	db $ff, $0f
	dw @song3ref588
	db $ff, $0f
	dw @song3ref588
	db $fd
	dw @song3ch3loop
@song3ch4:
@song3ch4loop:
@song3ref633:
	db $f7, $f7, $f7, $97, $f7, $f7, $f7, $97, $f7, $f7, $f7, $97, $f7, $f7, $f7, $97
	db $ff, $10
	dw @song3ref633
	db $ff, $10
	dw @song3ref633
	db $ff, $10
	dw @song3ref633
	db $fd
	dw @song3ch4loop
@song4ch0:
@song4ch0loop:
	db $6a, <(@tempo_env_5_mid), >(@tempo_env_5_mid), $8c, $27, $f7, $91, $2e, $91, $6b, $30, $a5, $29, $91, $2d, $91, $30, $a5
	db $2d, $a5, $6b, $33, $91, $30, $91, $29, $e1, $26, $91, $6b, $26, $e1, $3a, $91, $16, $a5, $6b, $16, $91, $16, $e1, $13
	db $a5, $6b, $13, $b9, $13, $a5, $18, $91, $18, $91, $1f, $91, $6b, $21, $e1, $22, $b9, $6b, $33, $cd, $2e, $cd, $6b, $2d
	db $e1, $2b, $91, $00, $a5, $6b, $2b, $91, $32, $e1, $33, $a5, $6b, $35, $91, $1a, $a5, $1d, $a5, $24, $b9, $6b, $00, $b9
	db $21, $91, $24, $91, $00, $91, $1d, $a5, $6b, $21, $f7, $a5, $6b, $26, $a5, $27, $91, $27, $91, $2d, $91, $26, $b9, $6b
	db $27, $91, $2e, $91, $00, $a5, $2d, $91, $27, $b9, $6b, $27, $a5, $00, $b9, $1a, $91, $15, $a5, $6b, $1b, $91, $1a, $b9
	db $1a, $a5, $21, $91, $26, $91, $6b, $24, $f7, $91, $26, $91, $6b, $1f, $91, $00, $a5, $16, $a5, $1b, $b9, $6b, $21, $cd
	db $1d, $b9, $24, $91, $6b, $1f, $b9, $1d, $cd, $00, $91, $6b, $21, $91, $00, $f5, $33, $91, $6b, $32, $91, $2d, $91, $00
	db $91, $2d, $a5, $1f, $a5, $1a, $91, $6b, $1b, $a5, $00, $b9, $1d, $a5, $1d, $91, $6b, $1b, $b9, $21, $91, $1b, $91, $15
	db $a5, $00, $91, $6b, $13, $91, $13, $b9, $00, $b9, $13, $91, $6b, $00, $a5, $18, $91, $1a, $91, $21, $cd, $6b, $00, $b9
	db $1f, $a5, $00, $b9, $6b, $13, $b9, $13, $a5, $13, $91, $13, $a5, $6b, $33, $f7, $a5, $6b, $33, $b9, $32, $91, $32, $91
	db $00, $b9, $6b, $22, $f7, $91, $21, $91, $fd
	dw @song4ch0loop
@song4ch1:
@song4ch1loop:
	db $8c, $2d, $91, $2d, $a5, $30, $91, $2b, $cd, $24, $e1, $27, $a5, $26, $91, $3a, $91, $3e, $91, $00, $91, $3f, $a5, $3c
	db $b9, $3a, $f7, $a5, $3e, $e1, $3c, $b9, $00, $91, $3a, $91, $00, $f5, $13, $b9, $13, $b9, $1a, $a5, $1b, $91, $00, $e1
	db $1d, $91, $1d, $91, $1d, $91, $16, $a5, $1b, $91, $21, $91, $00, $b9, $27, $91, $22, $a5, $1b, $91, $16, $91, $1d, $91
	db $16, $91, $18, $91, $13, $a5, $13, $f5, $16, $a5, $00, $a5, $15, $91, $13, $b9, $18, $91, $1f, $f5, $1d, $91, $18, $91
	db $16, $91, $15, $91, $00, $91, $15, $91, $13, $b9, $16, $a5, $16, $a5, $13, $91, $13, $91, $16, $a5, $00, $a5, $1a, $b9
	db $15, $91, $13, $a5, $15, $f7, $a5, $15, $91, $15, $91, $00, $cd, $16, $a5, $1d, $91, $24, $a5, $13, $91, $00, $a5, $18
	db $91, $26, $91, $21, $a5, $1b, $a5, $15, $cd, $00, $91, $13, $91, $13, $a5, $13, $a5, $13, $a5, $1a, $a5, $18, $f5, $13
	db $f5, $1a, $a5, $1f, $91, $3a, $cd, $00, $b9, $3a, $91, $37, $a5, $35, $cd, $39, $91, $33, $91, $00, $a5, $3c, $e1, $41
	db $a5, $1b, $a5, $1d, $91, $1a, $91, $16, $a5, $1a, $a5, $00, $a5, $16, $a5, $13, $a5, $13, $a5, $18, $91, $00, $b9, $24
	db $91, $2b, $91, $26, $a5, $1f, $b9, $32, $91, $39, $a5, $37, $91, $3e, $f5, $41, $91, $00, $91, $41, $b9, $3f, $91, $3e
	db $91, $37, $91, $3c, $91, $fd
	dw @song4ch1loop
@song4ch2:
@song4ch2loop:
	db $98, $39, $f7, $91, $35, $91, $35, $a5, $35, $91, $35, $a5, $35, $b9, $35, $b9, $35, $cd, $35, $91, $35, $f7, $a5, $35
	db $91, $35, $91, $35, $a5, $35, $cd, $00, $e1, $2d, $a5, $33, $91, $35, $b9, $35, $91, $2e, $b9, $32, $91, $30, $b9, $2e
	db $91, $32, $cd, $33, $b9, $35, $e1, $35, $91, $35, $e1, $35, $a5, $35, $91, $35, $a5, $35, $e1, $35, $a5, $35, $b9, $35
	db $b9, $35, $91, $32, $a5, $2d, $e1, $33, $91, $2d, $91, $00, $a5, $27, $91, $00, $91, $1f, $91, $2d, $91, $27, $a5, $00
	db $e1, $1f, $91, $1d, $a5, $1d, $cd, $24, $a5, $24, $f7, $a5, $26, $91, $13, $91, $18, $f5, $16, $91, $1a, $91, $1b, $b9
	db $1f, $b9, $18, $91, $16, $91, $1a, $f5, $16, $91, $16, $e1, $18, $a5, $1f, $f5, $21, $a5, $00, $e1, $2e, $91, $32, $a5
	db $00, $b9, $35, $e1, $35, $b9, $00, $b9, $21, $a5, $00, $91, $22, $91, $1b, $f5, $21, $a5, $00, $f5, $1a, $f7, $a5, $16
	db $b9, $1d, $a5, $00, $b9, $21, $f7, $a5, $1b, $a5, $1b, $e1, $00, $91, $1f, $f7, $a5, $fd
	dw @song4ch2loop
@song4ch3:
@song4ch3loop:
@song4ref710:
	db $90, $20, $a5, $20, $a5, $94, $29, $a5, $96, $36, $a5, $90, $20, $a5, $20, $a5, $94, $29, $a5, $96, $36, $a5, $90, $20
	db $a5, $20, $a5, $94, $29, $a5, $96, $36, $a5, $90, $20, $a5, $20, $a5, $94, $29, $a5, $96, $36, $a5
	db $ff, $20
	dw @song4ref710
	db $ff, $20
	dw @song4ref710
	db $ff, $20
	dw @song4ref710
	db $ff, $20
	dw @song4ref710
	db $ff, $20
	dw @song4ref710
	db $ff, $20
	dw @song4ref710
	db $ff, $20
	dw @song4ref710
	db $fd
	dw @song4ch3loop
@song4ch4:
@song4ch4loop:
@song4ref779:
	db $f7, $a7, $f7, $a7, $f7, $a7, $f7, $a7, $f7, $a7, $f7, $a7, $f7, $a7, $f7, $a7, $f7, $a7, $f7, $a7, $f7, $a7, $f7, $a7
	db $f7, $a7, $f7, $a7, $f7, $a7, $f7, $a7
	db $ff, $20
	dw @song4ref779
	db $fd
	dw @song4ch4loop
@song5ch0:
@song5ch0loop:
	db $6a, <(@tempo_env_9_mid), >(@tempo_env_9_mid), $00, $8f, $8c, $0f, $8f, $11, $a1, $0d, $8f, $0d, $c5, $0f, $b3, $0d, $8f
	db $00, $b3, $6b, $0d, $8f, $0f, $b3, $16, $8f, $11, $a1, $0d, $d7, $0d, $8f, $2e, $b3, $6b, $00, $d7, $2c, $c5, $27, $a1
	db $00, $8f, $2c, $8f, $25, $b3, $6b, $27, $a1, $29, $a1, $3a, $8f, $00, $f7, $95, $31, $b3, $6b, $2e, $c5, $2c, $8f, $00
	db $f7, $b9, $1d, $8f, $6b, $19, $a1, $1b, $8f, $22, $e9, $00, $8f, $22, $c5, $1d, $a1, $6b, $16, $8f, $1b, $b3, $1b, $a1
	db $19, $c5, $20, $a1, $19, $c5, $6b, $20, $b3, $1b, $8f, $19, $a1, $19, $b3, $20, $8f, $25, $b3, $00, $b3, $6b, $2e, $c5
	db $35, $8f, $2e, $8f, $33, $8f, $2e, $f7, $a7, $6b, $29, $8f, $22, $8f, $27, $8f, $2e, $a1, $31, $b3, $31, $b3, $38, $b3
	db $38, $8f, $38, $8f, $6b, $3a, $b3, $3a, $8f, $38, $d7, $3a, $f7, $83, $6b, $35, $a1, $00, $a1, $0f, $a1, $22, $a1, $29
	db $a1, $25, $c5, $00, $a1, $6b, $29, $f7, $83, $27, $b3, $25, $e9, $6b, $22, $c5, $29, $b3, $22, $a1, $22, $8f, $1d, $b3
	db $25, $8f, $00, $8f, $1d, $8f, $6b, $1d, $a1, $16, $e9, $11, $d7, $19, $b3, $6b, $1b, $c5, $1d, $8f, $20, $a1, $1b, $b3
	db $00, $b3, $25, $b3, $fd
	dw @song5ch0loop
@song5ch1:
@song5ch1loop:
	db $8c, $1d, $f7, $b9, $00, $8f, $29, $8f, $22, $8f, $22, $8f, $1b, $a1, $31, $b3, $2e, $a1, $00, $c5, $11, $c5, $11, $8f
	db $00, $8f, $14, $8f, $16, $8f, $0f, $b3, $16, $d7, $00, $f7, $83, $14, $a1, $1b, $b3, $20, $8f, $1d, $8f, $16, $f7, $83
	db $19, $8f, $11, $8f, $00, $e9, $0d, $c5, $0f, $e9, $14, $d7, $0f, $8f, $0f, $b3, $0d, $f7, $83, $0d, $f7, $a7, $0d, $e9
	db $11, $8f, $11, $b3, $16, $a1, $1d, $d7, $00, $e9, $11, $c5, $00, $d7, $19, $f7, $83, $1d, $a1, $25, $8f, $29, $f7, $a7
	db $2e, $c5, $31, $b3, $00, $b3, $35, $c5, $3a, $8f, $35, $a1, $35, $8f, $35, $8f, $3a, $8f, $3a, $8f, $3a, $8f, $38, $d7
	db $38, $f7, $a7, $3a, $8f, $11, $f7, $b9, $0f, $8f, $31, $c5, $31, $a1, $33, $8f, $38, $c5, $31, $c5, $2e, $a1, $2e, $8f
	db $33, $a1, $33, $a1, $2e, $d7, $31, $d7, $31, $c5, $2e, $a1, $35, $8f, $14, $b3, $0d, $8f, $11, $b3, $19, $c5, $11, $a1
	db $fd
	dw @song5ch1loop
@song5ch2:
@song5ch2loop:
	db $00, $d7, $98, $27, $b3, $2c, $e9, $00, $a1, $1d, $a1, $1b, $f7, $a7, $00, $8f, $27, $8f, $29, $a1, $29, $8f, $27, $d7
	db $29, $a1, $2e, $8f, $29, $d7, $22, $b3, $00, $b3, $22, $a1, $20, $8f, $1b, $f7, $a7, $20, $8f, $20, $8f, $19, $8f, $14
	db $f7, $cb, $0d, $8f, $0d, $a1, $00, $f7, $a7, $14, $a1, $1b, $8f, $00, $a1, $1b, $a1, $16, $a1, $11, $c5, $0d, $a1, $0d
	db $f7, $95, $00, $a1, $0d, $f7, $b9, $0d, $b3, $0f, $8f, $0f, $d7, $0d, $a1, $0d, $8f, $0d, $8f, $0d, $b3, $14, $8f, $1b
	db $8f, $20, $a1, $1b, $a1, $16, $f7, $f7, $89, $0f, $a1, $14, $a1, $19, $8f, $19, $d7, $00, $e9, $f7, $cd, $25, $c5, $25
	db $8f, $00, $b3, $20, $f7, $83, $20, $e9, $00, $f7, $83, $25, $a1, $00, $b3, $2e, $c5, $00, $8f, $2c, $a1, $00, $8f, $2e
	db $b3, $00, $d7, $2e, $b3, $2e, $8f, $2e, $c5, $27, $8f, $25, $8f, $27, $8f, $16, $e9, $22, $b3, $fd
	dw @song5ch2loop
@song5ch3:
@song5ch3loop:
@song5ref559:
	db $c7, $96, $36, $e9, $36, $a1, $94, $29, $c5, $c7, $96, $36, $e9, $36, $a1, $94, $29, $c5
	db $ff, $0e
	dw @song5ref559
	db $ff, $0e
	dw @song5ref559
	db $ff, $0e
	dw @song5ref559
	db $ff, $0e
	dw @song5ref559
	db $ff, $0e
	dw @song5ref559
	db $ff, $0e
	dw @song5ref559
	db $ff, $0e
	dw @song5ref559
	db $fd
	dw @song5ch3loop
@song5ch4:
@song5ch4loop:
@song5ref602:
	db $f7, $f7, $af, $f7, $f7, $af, $f7, $f7, $af, $f7, $f7, $af
	db $ff, $0c
	dw @song5ref602
	db $ff, $0c
	dw @song5ref602
	db $ff, $0c
	dw @song5ref602
	db $fd
	dw @song5ch4loop
@song6ch0:
@song6ch0loop:
	db $6a, <(@tempo_env_11_mid), >(@tempo_env_11_mid), $8c, $23, $d5, $1c, $eb, $20, $a9, $00, $a9, $23, $93, $28, $93, $25
	db $93, $6b, $2c, $93, $34, $93, $00, $93, $34, $a9, $31, $f7, $e1, $1c, $93, $6b, $1e, $a9, $00, $bf, $14, $a9, $12, $a9
	db $10, $f7, $9f, $6b, $00, $bf, $14, $a9, $10, $a9, $10, $93, $10, $bf, $17, $93, $1e, $d5, $6b, $17, $93, $14, $93, $14
	db $f7, $9f, $10, $93, $28, $bf, $36, $93, $3b, $93, $38, $93, $6b, $31, $93, $2a, $93, $2c, $f7, $e1, $12, $a9, $17, $93
	db $1e, $93, $6b, $1c, $d5, $1c, $a9, $17, $a9, $00, $93, $10, $f7, $89, $14, $93, $6b, $14, $f7, $b5, $1c, $bf, $20, $d5
	db $23, $93, $6b, $28, $bf, $23, $a9, $00, $93, $17, $eb, $1c, $a9, $17, $bf, $6b, $28, $a9, $2a, $93, $2a, $93, $31, $bf
	db $2f, $d5, $2f, $a9, $00, $bf, $6b, $f7, $8b, $38, $93, $3d, $93, $36, $bf, $2f, $eb, $6b, $00, $a9, $38, $93, $3b, $a9
	db $3d, $93, $00, $bf, $3d, $bf, $3d, $93, $3d, $bf, $6b, $3d, $f7, $9f, $00, $bf, $3d, $bf, $3d, $bf, $6b, $3b, $a9, $00
	db $eb, $3d, $93, $3b, $93, $00, $f7, $89, $34, $93, $6b, $2f, $93, $28, $f7, $b5, $25, $a9, $23, $93, $28, $93, $23, $93
	db $28, $a9, $6b, $28, $eb, $00, $f7, $b5, $2c, $bf, $fd
	dw @song6ch0loop
@song6ch1:
@song6ch1loop:
	db $8c, $28, $eb, $28, $93, $2c, $a9, $2c, $f7, $9f, $2a, $93, $23, $93, $28, $93, $25, $a9, $28, $d5, $28, $d5, $00, $93
	db $1e, $bf, $00, $a9, $17, $93, $17, $d5, $1e, $d5, $00, $93, $2a, $a9, $2f, $93, $00, $93, $2c, $93, $34, $a9, $38, $f7
	db $89, $34, $93, $2f, $eb, $36, $93, $00, $f7, $9f, $25, $f7, $89, $25, $bf, $00, $d5, $2c, $a9, $25, $a9, $2a, $d5, $2c
	db $a9, $31, $a9, $34, $93, $00, $a9, $23, $93, $2a, $d5, $2c, $93, $00, $93, $23, $93, $2a, $bf, $2c, $a9, $2a, $93, $28
	db $93, $20, $bf, $1c, $eb, $00, $93, $28, $93, $28, $93, $23, $bf, $19, $93, $14, $d5, $14, $93, $14, $eb, $12, $d5, $00
	db $93, $1e, $a9, $19, $93, $00, $bf, $1c, $f7, $9f, $19, $a9, $20, $93, $20, $d5, $19, $93, $19, $93, $14, $bf, $2c, $a9
	db $2a, $93, $28, $a9, $00, $a9, $1c, $93, $1e, $93, $31, $93, $2c, $93, $2a, $93, $2c, $93, $25, $a9, $28, $93, $20, $bf
	db $25, $93, $28, $93, $20, $a9, $00, $a9, $17, $93, $1c, $a9, $23, $a9, $1c, $93, $1c, $a9, $00, $f7, $89, $1e, $a9, $23
	db $93, $00, $d5, $2a, $f7, $9f, $00, $a9, $2a, $93, $31, $a9, $00, $a9, $3d, $93, $38, $a9, $3d, $d5, $38, $d5, $3b, $bf
	db $10, $bf, $00, $bf, $10, $93, $10, $93, $17, $a9, $19, $bf, $fd
	dw @song6ch1loop
@song6ch2:
@song6ch2loop:
	db $98, $2c, $a9, $25, $a9, $23, $bf, $20, $d5, $20, $d5, $20, $93, $1e, $bf, $00, $93, $25, $f7, $9f, $2a, $bf, $2c, $a9
	db $2f, $d5, $28, $a9, $20, $a9, $23, $d5, $25, $93, $00, $a9, $2c, $93, $2c, $f7, $e1, $31, $eb, $2f, $93, $28, $f7, $89
	db $2c, $eb, $34, $eb, $34, $93, $2f, $bf, $2a, $a9, $31, $93, $1c, $93, $1c, $bf, $20, $eb, $28, $f7, $9f, $28, $d5, $23
	db $eb, $1c, $bf, $1c, $f7, $f7, $ab, $1c, $93, $00, $93, $1c, $a9, $00, $a9, $1e, $a9, $20, $a9, $20, $a9, $25, $a9, $20
	db $a9, $23, $f7, $b5, $00, $d5, $20, $a9, $28, $a9, $28, $bf, $23, $d5, $20, $d5, $25, $d5, $1e, $93, $20, $93, $00, $eb
	db $20, $eb, $25, $eb, $00, $bf, $23, $eb, $28, $93, $23, $f7, $9f, $2a, $bf, $23, $f7, $b5, $00, $eb, $2a, $f7, $f7, $ed
	db $31, $93, $2f, $d5, $36, $a9, $34, $a9, $38, $bf, $31, $d5, $fd
	dw @song6ch2loop
@song6ch3:
@song6ch3loop:
@song6ref617:
	db $90, $20, $a9, $96, $36, $a9, $36, $a9, $90, $20, $a9, $20, $d5, $92, $2a, $d5, $90, $20, $a9, $96, $36, $a9, $36, $a9
	db $90, $20, $a9, $20, $d5, $92, $2a, $d5
	db $ff, $18
	dw @song6ref617
	db $ff, $18
	dw @song6ref617
	db $ff, $18
	dw @song6ref617
	db $ff, $18
	dw @song6ref617
	db $ff, $18
	dw @song6ref617
	db $ff, $18
	dw @song6ref617
	db $ff, $18
	dw @song6ref617
	db $fd
	dw @song6ch3loop
@song6ch4:
@song6ch4loop:
@song6ref674:
	db $f7, $f7, $ef, $f7, $f7, $ef, $f7, $f7, $ef, $f7, $f7, $ef, $f7, $f7, $ef
	db $ff, $0f
	dw @song6ref674
	db $ff, $0f
	dw @song6ref674
	db $f7, $f7, $ef, $fd
	dw @song6ch4loop
@song7ch0:
@song7ref1:
	db $88
@song7ref2:
	db $2b, $9d, $f9, $9d, $2e, $9d, $f9, $8d, $2b, $8d, $f9, $8d, $2b, $8d, $30, $8d, $f9, $8d, $2b, $8d, $f9, $8d, $29, $8d
	db $f9, $8d, $6b, $2b, $9d, $f9, $9d, $32, $9d, $f9, $8d, $2b, $8d, $f9, $8d, $2b, $8d, $33, $8d, $f9, $8d, $32, $8d, $f9
	db $8d, $2e, $8d, $f9, $8d, $6b, $2b, $8d, $f9, $8d, $32, $8d, $f9, $8d, $37, $89, $f9, $91, $2b, $8d, $29, $8d, $f9, $8d
	db $29, $8d, $26, $8d, $f9, $8d, $2d, $8d, $f9, $8d, $2b, $9d, $6b, $8f, $f9, $8d, $00, $f7, $e5, $6b
	db $ff, $58
	dw @song7ref2
	db $6b, $f7, $f7, $8f, $6b, $f7, $f7, $8f, $6b, $f7, $f7, $8f, $6b, $f7, $f7, $8f, $6b, $f7, $f7, $8f, $6b, $f7, $f7, $8f
	db $6b, $f7, $f7, $8f, $6b, $f7, $f7, $8f
@song7ch0loop:
	db $6a, <(@tempo_env_8_mid), >(@tempo_env_8_mid)
	db $ff, $58
	dw @song7ref1
	db $6b
	db $ff, $58
	dw @song7ref2
	db $6b, $9f, $82
@song7ref143:
	db $32, $cd, $35, $ad, $35, $9d, $34, $bd, $6b, $9f, $32, $cd, $35, $ad, $34, $9d, $32, $9d, $2f, $9d, $6b, $9f, $2e, $dd
	db $2e, $8d, $30, $dd, $30, $8d, $6b, $30, $9d, $32, $dd, $30, $8d, $32, $ed, $6b, $9f
	db $ff, $24
	dw @song7ref143
	db $6b, $00, $f7, $f7, $8d, $6b, $f7, $f7, $8f, $6b, $f7, $f7, $8f, $6b, $f7, $f7, $8f, $fd
	dw @song7ch0loop
@song7ch1:
@song7ref207:
	db $9f, $8a
@song7ref209:
	db $2b, $8d, $f9, $8d, $2b, $8d, $f9, $8d, $2e, $8d, $f9, $8d, $2e, $8d, $2b, $8d, $f9, $8d, $2b, $8d, $30, $8d, $f9, $8d
	db $2b, $8d, $f9, $8d, $29, $8d, $f9, $8d, $2b, $8d, $f9, $8d, $2b, $8d, $f9, $8d, $32, $8d, $f9, $8d, $32, $8d, $2b, $8b
	db $f9, $8f, $2b, $8d, $33, $8d, $f9, $8d, $32, $8d, $f9, $8d, $2e, $8d, $f9, $8d, $2b, $8d, $f9, $8d, $32, $8d, $2b, $8d
	db $37, $89, $f9, $91, $2b, $8d, $29, $8d, $f9, $8d, $29, $8d, $26, $8d, $f9, $8d, $2d, $8d, $f9, $8d, $2b, $8d, $f9, $8d
	db $2b, $8d, $f9, $8d, $2b, $8d, $f9, $8d, $00, $f7, $a5, $9f
	db $ff, $6b
	dw @song7ref209
@song7ref320:
	db $f7, $f7, $8f, $f7, $f7, $8f, $f7, $f7, $8f, $f7, $f7, $8f, $f7, $f7, $8f, $f7, $f7, $8f, $f7, $f7, $8f, $f7, $f7, $8f
@song7ch1loop:
	db $ff, $6d
	dw @song7ref207
	db $ff, $6c
	dw @song7ref209
	db $82
@song7ref352:
	db $2f, $cd, $30, $ad, $30, $9d, $30, $bd, $9f, $2f, $cd, $30, $9d, $2d, $8d, $2b, $9d, $2f, $9d, $26, $9d, $9f, $2b, $dd
	db $2b, $8d, $2d, $dd, $2d, $8d, $2d, $9d, $2f, $dd, $2d, $8d, $2f, $ed, $9f
	db $ff, $26
	dw @song7ref352
	db $00, $f7, $f7, $8d, $f7, $f7, $8f, $f7, $f7, $8f, $f7, $f7, $8f, $fd
	dw @song7ch1loop
@song7ch2:
	db $ff, $18
	dw @song7ref320
@song7ref413:
	db $80
@song7ref414:
	db $1f, $bd, $2b, $ad, $1d, $9d, $29, $8d, $1a, $9d, $26, $9d, $1d, $9d, $1f, $bd, $2b, $cd, $1a, $8d, $26, $9d, $29, $9d
	db $2b, $9d, $1b, $bd, $27, $ad, $1d, $9d, $29, $8d, $1a, $9d, $1d, $9d, $1f, $9d, $2b, $9d, $00, $ed, $29, $8d, $25, $9d
	db $24, $9d, $22, $9d
	db $ff, $34
	dw @song7ref414
@song7ch2loop:
	db $ff, $34
	dw @song7ref413
	db $ff, $34
	dw @song7ref414
	db $ff, $34
	dw @song7ref414
	db $ff, $34
	dw @song7ref414
	db $ff, $34
	dw @song7ref414
	db $fd
	dw @song7ch2loop
@song7ch3:
	db $f7, $f7, $8f, $f7, $f7, $8f, $f7, $f7, $8f, $f7, $f7, $8f, $f7, $f7, $8f, $f7, $f7, $8f, $f7, $f7, $8f, $bd, $86, $24
	db $8f, $25, $8d, $26, $8d, $27, $8d, $28, $8d, $29, $8d, $2a, $8d, $2b, $8d, $2c, $8d, $2d, $8d, $2e, $8d, $2f, $8b, $00
@song7ref536:
	db $84
@song7ref537:
	db $2a, $8d, $2a, $8d, $2a, $8d, $2a, $ad, $2a, $9d, $2a, $ad, $2a, $bd, $2a, $8d, $2a, $8d, $2a, $8d, $2a, $8d, $2a, $ad
	db $2a, $9d, $2a, $ad, $2a, $bd, $2a, $8d
	db $ff, $20
	dw @song7ref537
	db $ff, $20
	dw @song7ref537
	db $ff, $20
	dw @song7ref537
@song7ch3loop:
	db $ff, $20
	dw @song7ref536
	db $ff, $20
	dw @song7ref537
	db $ff, $20
	dw @song7ref537
	db $ff, $20
	dw @song7ref537
	db $ff, $20
	dw @song7ref537
	db $ff, $20
	dw @song7ref537
	db $ff, $20
	dw @song7ref537
	db $ff, $20
	dw @song7ref537
	db $ff, $20
	dw @song7ref537
	db $ff, $20
	dw @song7ref537
	db $fd
	dw @song7ch3loop
@song7ch4:
	db $ff, $18
	dw @song7ref320
	db $f7, $f7, $8f, $f7, $f7, $8f, $f7, $f7, $8f, $f7, $f7, $8f, $06, $ed, $06, $9d, $06, $8d, $06, $bd, $06, $9d, $06, $f7
	db $95, $06, $8d, $06, $9d, $06, $bd, $06, $bd, $06, $dd, $06, $9d, $06, $9d, $06, $9d, $06, $bd, $06, $cd, $06, $8d, $06
	db $9d, $06, $9d, $06, $9d
@song7ch4loop:
@song7ref669:
	db $06, $bd, $07, $ad, $06, $9d, $06, $8d, $06, $9d, $07, $9d, $06, $9d, $06, $bd, $07, $cd, $06, $8d, $06, $9d, $07, $bd
	db $06, $bd, $07, $dd, $06, $9d, $07, $9d, $06, $9d, $06, $bd, $07, $cd, $06, $8d, $06, $9d, $07, $9d, $06, $9d
	db $ff, $2e
	dw @song7ref669
	db $ff, $2e
	dw @song7ref669
	db $ff, $2e
	dw @song7ref669
	db $ff, $2e
	dw @song7ref669
	db $fd
	dw @song7ch4loop
